
image:
  file: .gitpod.Dockerfile
# This is to get rid of the annoying popup feel free to leave this out
ports:
  # - port: 8000
    # onOpen: open-preview
  - port: 9000
    onOpen: ignore
vscode:
  extensions:
    - felixfbecker.php-debug@1.13.0:WX8Y3EpQk3zgahy41yJtNQ==
tasks:
  - init: bash .gitpod-init.sh
    command: php artisan migrate --seed && php artisan serve
